import type { Metadata } from "next";
import {
    Playfair_Display,
    Cormorant_Garamond,
    DM_Serif_Display,
    Fraunces,
    Bodoni_Moda,
    Montserrat,
    Oswald,
    Raleway,
    Josefin_Sans,
    Cinzel,
    Inter,
    DM_Sans,
    Plus_Jakarta_Sans,
    Outfit,
    Nunito,
    Lato,
    Open_Sans,
    Jost,
    Source_Sans_3,
    Mulish,
} from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import { FONT_CSS_MAP } from "@/lib/constants/fonts";
import Footer from "@/components/Footer";
import { GoogleAnalytics } from "@next/third-parties/google";
import { Toaster } from "sonner";
import { getEtablissement, getSiteConfig } from "@/lib/api";

// --- Polices de titres ---
const playfairDisplay = Playfair_Display({
    variable: "--font-playfair-display",
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal", "italic"],
});

const cormorantGaramond = Cormorant_Garamond({
    variable: "--font-cormorant-garamond",
    subsets: ["latin"],
    weight: ["400", "600", "700"],
    style: ["normal", "italic"],
});
const dmSerifDisplay = DM_Serif_Display({
    variable: "--font-dm-serif-display",
    subsets: ["latin"],
    weight: ["400"],
    style: ["normal", "italic"],
});
const fraunces = Fraunces({
    variable: "--font-fraunces",
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal", "italic"],
});
const bodoniModa = Bodoni_Moda({
    variable: "--font-bodoni-moda",
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal", "italic"],
});
const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
    weight: ["400", "600", "700"],
});
const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});
const raleway = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
    weight: ["400", "600", "700"],
});
const josefinSans = Josefin_Sans({
    variable: "--font-josefin-sans",
    subsets: ["latin"],
    weight: ["400", "600", "700"],
});
const cinzel = Cinzel({
    variable: "--font-cinzel",
    subsets: ["latin"],
    weight: ["400", "700"],
});

// --- Polices de corps ---
const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});
const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
});
const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-plus-jakarta-sans",
    subsets: ["latin"],
});
const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});
const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
});
const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["400", "700"],
});
const openSans = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin"],
});
const jost = Jost({
    variable: "--font-jost",
    subsets: ["latin"],
});
const sourceSans3 = Source_Sans_3({
    variable: "--font-source-sans-3",
    subsets: ["latin"],
});
const mulish = Mulish({
    variable: "--font-mulish",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const allFontVariables = [
        playfairDisplay.variable,
        cormorantGaramond.variable,
        dmSerifDisplay.variable,
        fraunces.variable,
        bodoniModa.variable,
        montserrat.variable,
        oswald.variable,
        raleway.variable,
        josefinSans.variable,
        cinzel.variable,
        inter.variable,
        dmSans.variable,
        plusJakartaSans.variable,
        outfit.variable,
        nunito.variable,
        lato.variable,
        openSans.variable,
        jost.variable,
        sourceSans3.variable,
        mulish.variable,
    ].join(" ");

    const siteData = await getSiteConfig();
    const etablissement = await getEtablissement();

    const enabledFeatures = etablissement.features;

    console.log(enabledFeatures);

    //On fournit le thème dynamique
    const dynamicStyle = {
        "--primary": siteData?.theme?.primary?.background,
        "--primary-foreground": siteData?.theme?.primary?.foreground,
        "--accent": siteData?.theme?.accent?.background,
        "--accent-foreground": siteData?.theme?.accent?.foreground,
        "--radius": siteData?.theme?.borderRadius,
        "--site-font-title":
            FONT_CSS_MAP[siteData?.theme?.fonts?.title ?? ""] ??
            "'Playfair Display', ui-serif, Georgia, serif",
        "--site-font-body":
            FONT_CSS_MAP[siteData?.theme?.fonts?.body ?? ""] ??
            "'Inter', ui-sans-serif, system-ui, sans-serif",
    } as React.CSSProperties;

    return (
        <html lang="en">
            <body
                style={dynamicStyle}
                className={`${allFontVariables} antialiased overflow-x-hidden`}
            >
                <Header
                    data={siteData.header}
                    enabledFeatures={enabledFeatures}
                />
                <main>{children}</main>
                <Footer etablissement={etablissement} />
                {process.env.NEXT_PUBLIC_GA_ID && (
                    <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
                )}
                <Toaster />
            </body>
        </html>
    );
}
